FROM node:14.16.0-alpine3.13 AS build-stage

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install
COPY . ./
RUN yarn build

FROM nginx:1.12-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80