# Generated by Django 3.2.5 on 2021-07-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
